workflows:
  android-release:
    name: Android APK Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Clean
        script: flutter clean
      - name: Install Dependencies
        script: flutter pub get
      - name: Force Create Android
        script: |
          rm -rf android ios
          flutter create --platforms=android .
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
