name: somobay_app
description: সমবায় সমিতি ম্যানেজমেন্ট অ্যাপ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3

flutter:
  uses-material-design: true
